export const IMPOSTOR_ALPHA_CUTOFF = 0.18;
export const IMPOSTOR_AERIAL_FADE_START = 0.42;
export const IMPOSTOR_AERIAL_FADE_END = 0.68;
export const IMPOSTOR_BASE_COLOR_BLEND = 0.52;
export const IMPOSTOR_ROOT_LIGHT_MIN = 0.88;
export const IMPOSTOR_ROOT_LIGHT_MAX = 1.01;
