import {
  NON_NEGATIVE_NUMBER_RULE,
  POSITIVE_INTEGER_RULE,
  POSITIVE_NUMBER_RULE,
  UINT32_INTEGER_RULE,
  type ConfigNumberRule,
} from "../config/FlatConfigValueReader";
import type { WorldConfig } from "./WorldConfig";

const MAX_TERRAIN_STREAM_RADIUS = 16;
const MAX_TERRAIN_NEAR_RESOLUTION = 129;
const MAX_TERRAIN_MID_RESOLUTION = 65;
const MAX_TERRAIN_FAR_RESOLUTION = 33;
/**
 * Shell bounds. The spacing ceiling keeps the shell from coarsening past the
 * point where its silhouette stops resembling the terrain it stands in for,
 * and the ring/growth ceilings bound the apron: sixteen rings at 1.5 already
 * reach far beyond any fog this world uses.
 */
const MAX_HORIZON_SPACING = 64;
const MAX_HORIZON_APRON_RINGS = 32;
const MAX_HORIZON_APRON_GROWTH = 1.5;

export type WorldConfigSchema = {
  [Key in keyof WorldConfig]: Readonly<ConfigNumberRule>;
};

export const WORLD_CONFIG_SCHEMA: WorldConfigSchema = {
  seed: UINT32_INTEGER_RULE,
  worldSize: POSITIVE_NUMBER_RULE,
  chunkSize: POSITIVE_NUMBER_RULE,
  terrainRadiusDesktop: {
    minimum: 1,
    maximum: MAX_TERRAIN_STREAM_RADIUS,
    integer: true,
  },
  terrainRadiusCompact: {
    minimum: 1,
    maximum: MAX_TERRAIN_STREAM_RADIUS,
    integer: true,
  },
  grassRadiusDesktop: POSITIVE_INTEGER_RULE,
  grassRadiusCompact: POSITIVE_INTEGER_RULE,
  terrainNearResolution: {
    minimum: 3,
    maximum: MAX_TERRAIN_NEAR_RESOLUTION,
    integer: true,
  },
  terrainMidResolution: {
    minimum: 3,
    maximum: MAX_TERRAIN_MID_RESOLUTION,
    integer: true,
  },
  terrainFarResolution: {
    minimum: 3,
    maximum: MAX_TERRAIN_FAR_RESOLUTION,
    integer: true,
  },
  terrainChunksPerFrame: POSITIVE_INTEGER_RULE,
  horizonEnabled: { minimum: 0, maximum: 1, integer: true },
  horizonSpacing: { minimum: 4, maximum: MAX_HORIZON_SPACING },
  horizonApronRings: { minimum: 0, maximum: MAX_HORIZON_APRON_RINGS, integer: true },
  horizonApronGrowth: { minimum: 1, maximum: MAX_HORIZON_APRON_GROWTH },
  grassChunksPerFrame: POSITIVE_INTEGER_RULE,
  grassPatchSize: POSITIVE_NUMBER_RULE,
  grassRenderBatchesPerAxis: POSITIVE_INTEGER_RULE,
  grassFarImpostorsPerPatch: { minimum: 1, maximum: 1, integer: true },
  grassBladesPerSquareMeterDesktop: { minimum: 4, maximum: 160 },
  grassBladesPerSquareMeterCompact: { minimum: 4, maximum: 160 },
  grassNearTileSize: POSITIVE_NUMBER_RULE,
  grassNearBladesPerSquareMeterDesktop: { minimum: 8, maximum: 180 },
  grassNearBladesPerSquareMeterCompact: { minimum: 8, maximum: 180 },
  grassUltraNearDistance: POSITIVE_NUMBER_RULE,
  grassUltraNearTransitionDistance: POSITIVE_NUMBER_RULE,
  grassUltraNearDensityMultiplier: { minimum: 1, maximum: 3 },
  grassUltraNearDensityMultiplierCompact: { minimum: 1, maximum: 3 },
  grassNearBridgeDistance: POSITIVE_NUMBER_RULE,
  grassNearBridgeTransitionDistance: POSITIVE_NUMBER_RULE,
  grassClumpRadiusScaleMin: { minimum: 0.2, maximum: 0.5 },
  grassClumpRadiusScaleMax: { minimum: 0.2, maximum: 0.5 },
  grassClumpAspectMin: { minimum: 0.6, maximum: 1 },
  grassClumpAspectMax: { minimum: 1, maximum: 1.5 },
  grassClumpRadialExponent: { minimum: 0.5, maximum: 0.75 },
  grassClumpDominantDirectionWeight: { minimum: 0, maximum: 1 },
  grassClumpRadialDirectionWeight: { minimum: 0, maximum: 1 },
  grassMacroPatchWorldSize: { minimum: 16, maximum: 120 },
  grassMacroPatchStrength: { minimum: 0, maximum: 0.6 },
  grassWetDensityBoost: { minimum: 0, maximum: 0.6 },
  grassDryDensityReduction: { minimum: 0, maximum: 0.8 },
  grassRockDensityReduction: { minimum: 0, maximum: 0.9 },
  grassDisturbanceDensityReduction: { minimum: 0, maximum: 0.95 },
  grassWetHeightBoost: { minimum: 0, maximum: 0.4 },
  grassDryHeightReduction: { minimum: 0, maximum: 0.5 },
  grassDryColorStrength: { minimum: 0, maximum: 0.7 },
  grassMidBladeFraction: { minimum: 0.05, maximum: 1 },
  grassUnderlayerFraction: { minimum: 0, maximum: 0.6 },
  grassPatchJitter: { minimum: 0, maximum: 0.9 },
  grassInteractionStrength: { minimum: 0, maximum: 2 },
  grassInteractionSpeedForFullEffect: POSITIVE_NUMBER_RULE,
  grassLandingPulseRadius: POSITIVE_NUMBER_RULE,
  grassLandingPulseStrength: { minimum: 0, maximum: 2 },
  grassLandingPulseDecay: POSITIVE_NUMBER_RULE,
  grassTrailResolution: { minimum: 64, maximum: 1024, integer: true },
  grassTrailCoverage: POSITIVE_NUMBER_RULE,
  grassTrailRecoveryRate: POSITIVE_NUMBER_RULE,
  grassTrailFreshnessRate: POSITIVE_NUMBER_RULE,
  grassTrailMaxAngleDegrees: { minimum: 10, maximum: 85 },
  grassTrailWobbleFrequency: NON_NEGATIVE_NUMBER_RULE,
  grassTrailWobbleAmplitude: { minimum: 0, maximum: 0.6 },
  grassFootContactRadius: POSITIVE_NUMBER_RULE,
  grassFootContactStrength: { minimum: 0, maximum: 2 },
  grassBodyContactRadius: POSITIVE_NUMBER_RULE,
  grassBodyContactStrength: { minimum: 0, maximum: 2 },
  spawnSearchRadius: POSITIVE_NUMBER_RULE,
  spawnSearchStep: POSITIVE_NUMBER_RULE,
  spawnNeighborhoodRadius: POSITIVE_NUMBER_RULE,
  spawnEyeHeight: POSITIVE_NUMBER_RULE,
  spawnPitchDegrees: { minimum: -45, maximum: 15 },
  baseHeight: {},
  rollingHeight: NON_NEGATIVE_NUMBER_RULE,
  mountainHeight: NON_NEGATIVE_NUMBER_RULE,
  mountainScale: POSITIVE_NUMBER_RULE,
  detailScale: POSITIVE_NUMBER_RULE,
  waterEnabled: { minimum: 0, maximum: 1, integer: true },
  riverWidth: { minimum: 2, maximum: 40 },
  riverBankWidth: { minimum: 1, maximum: 30 },
  riverDepth: { minimum: 0.2, maximum: 8 },
  riverSpacing: { minimum: 160, maximum: 4000 },
  riverMeander: { minimum: 0, maximum: 600 },
  riverMaxAltitude: {},
  waterHumidityRadius: { minimum: 4, maximum: 120 },
  lakeSpacing: { minimum: 160, maximum: 2000 },
  lakeChance: { minimum: 0, maximum: 1 },
  lakeRadiusMin: { minimum: 8, maximum: 160 },
  lakeRadiusMax: { minimum: 8, maximum: 200 },
  lakeDepth: { minimum: 0.4, maximum: 16 },
  lakeShoreWidth: { minimum: 1, maximum: 40 },
  waterSurfaceOffset: { minimum: 0.01, maximum: 0.5 },
  waterOpacity: { minimum: 0.2, maximum: 1 },
  waterRippleStrength: { minimum: 0, maximum: 0.5 },
  waterRippleScale: { minimum: 0.01, maximum: 0.5 },
  waterFlowSpeed: { minimum: 0.1, maximum: 4 },
  waterFoamStrength: { minimum: 0, maximum: 2 },
  waterFresnelStrength: { minimum: 0, maximum: 4 },
  waterDepthFade: { minimum: 0.1, maximum: 10 },
  waterDetailDistance: { minimum: 20, maximum: 400 },
  waterLakeWaveStrength: { minimum: 0.1, maximum: 1 },
  waterRoughness: { minimum: 0.02, maximum: 0.5 },
  waterFlowNoiseScale: { minimum: 0.005, maximum: 0.25 },
  waterFlowNoiseStrength: { minimum: 0, maximum: 1 },
  waterCausticStrength: { minimum: 0, maximum: 1 },
  waterGlintStrength: { minimum: 0, maximum: 1 },
  waterStoneWakeStrength: { minimum: 0, maximum: 2 },
  waterStoneWakeLength: { minimum: 0.5, maximum: 12 },
  waterBedStrength: { minimum: 0, maximum: 1 },
  waterBedScale: { minimum: 0.02, maximum: 0.8 },
  waterBedRefraction: { minimum: 0, maximum: 2 },
  waterAlgaeStrength: { minimum: 0, maximum: 1 },
  pathWidth: { minimum: 0.5, maximum: 12 },
  pathBranchWidth: { minimum: 0.4, maximum: 12 },
  pathSpacing: { minimum: 120, maximum: 4000 },
  pathEdgeRoughness: { minimum: 0, maximum: 2 },
  pathGrassClearance: { minimum: 0, maximum: 4 },
  terrainGroundNoiseWorldSize: { minimum: 16, maximum: 256 },
  terrainGroundMesoStrength: { minimum: 0, maximum: 0.5 },
  terrainGroundMicroStrength: { minimum: 0, maximum: 0.35 },
  terrainGroundNormalStrength: { minimum: 0, maximum: 1 },
  terrainGroundCanopyDarkening: { minimum: 0, maximum: 0.5 },
  terrainPathCoreDarkening: { minimum: 0, maximum: 0.5 },
  terrainPathVergeDryness: { minimum: 0, maximum: 1 },
  grassMinAltitude: {},
  grassMaxAltitude: {},
  grassMaxSlopeDegrees: { minimum: 1, maximum: 89 },
  stonesEnabled: { minimum: 0, maximum: 1, integer: true },
  stoneCellSize: { minimum: 8, maximum: 64 },
  stoneDensity: { minimum: 0, maximum: 3 },
  stoneVariantsPerArchetype: { minimum: 2, maximum: 16, integer: true },
  stoneClusterChance: { minimum: 0, maximum: 1 },
  stoneGrassClearanceFeather: { minimum: 0.1, maximum: 2 },
  stoneRadiusDesktop: POSITIVE_INTEGER_RULE,
  stoneRadiusCompact: POSITIVE_INTEGER_RULE,
  stoneDetailRadius: POSITIVE_INTEGER_RULE,
  stoneDetailRadiusCompact: POSITIVE_INTEGER_RULE,
  stoneRenderBatchChunksPerAxis: { minimum: 1, maximum: 4, integer: true },
  stoneChunksPerFrame: POSITIVE_INTEGER_RULE,
  stoneVergeChance: { minimum: 0, maximum: 1 },
  stoneGrainStrength: { minimum: 0, maximum: 0.5 },
  stoneGrainSize: { minimum: 0.05, maximum: 4 },
  stoneGrainFadeDistance: { minimum: 2, maximum: 120 },
  stoneGrowthDetailStrength: { minimum: 0, maximum: 1 },
  stoneGrowthDetailSize: { minimum: 0.05, maximum: 2 },
  stoneGrowthDetailFadeDistance: { minimum: 2, maximum: 120 },
  stoneMossExposureStrength: { minimum: 0, maximum: 1 },
  stoneMossExposureAzimuthDegrees: { minimum: -360, maximum: 360 },
  stoneMossExposureElevationDegrees: { minimum: 0, maximum: 90 },
  stoneMossStreakStrength: { minimum: 0, maximum: 1 },
  grassNearDistance: POSITIVE_NUMBER_RULE,
  grassMidDistance: POSITIVE_NUMBER_RULE,
  grassFarDistance: POSITIVE_NUMBER_RULE,
  grassTransitionDistance: POSITIVE_NUMBER_RULE,
  grassHysteresisDistance: NON_NEGATIVE_NUMBER_RULE,
  flySpeed: POSITIVE_NUMBER_RULE,
  flyBoostMultiplier: POSITIVE_NUMBER_RULE,
  flyMinSpeed: POSITIVE_NUMBER_RULE,
  flyMaxSpeed: POSITIVE_NUMBER_RULE,
  initialAltitude: POSITIVE_NUMBER_RULE,
  initialDistance: POSITIVE_NUMBER_RULE,
  characterScale: POSITIVE_NUMBER_RULE,
  characterWalkSpeed: POSITIVE_NUMBER_RULE,
  characterRunSpeed: POSITIVE_NUMBER_RULE,
  characterAcceleration: POSITIVE_NUMBER_RULE,
  characterDeceleration: POSITIVE_NUMBER_RULE,
  characterTurnRate: POSITIVE_NUMBER_RULE,
  characterJumpSpeed: POSITIVE_NUMBER_RULE,
  characterGravity: POSITIVE_NUMBER_RULE,
  characterFallGravityMultiplier: { minimum: 1, maximum: 3 },
  characterAirControl: { minimum: 0, maximum: 1 },
  characterCoyoteTime: { minimum: 0, maximum: 0.5 },
  characterJumpBufferTime: { minimum: 0, maximum: 0.5 },
  characterJumpHoldTime: { minimum: 0, maximum: 0.5 },
  characterJumpHoldGravityScale: { minimum: 0.1, maximum: 1 },
  characterLandingRecoveryTime: { minimum: 0.05, maximum: 1 },
  characterLandingImpactForFullEffect: POSITIVE_NUMBER_RULE,
  characterCameraDistance: POSITIVE_NUMBER_RULE,
  characterCameraMinDistance: POSITIVE_NUMBER_RULE,
  characterCameraMaxDistance: POSITIVE_NUMBER_RULE,
  characterCameraLookHeight: POSITIVE_NUMBER_RULE,
  characterCameraElevationDegrees: { minimum: -80, maximum: 80 },
  characterCameraMinElevationDegrees: { minimum: -80, maximum: 80 },
  characterCameraMaxElevationDegrees: { minimum: -80, maximum: 80 },
  characterCameraFollowRate: POSITIVE_NUMBER_RULE,
  characterCameraGroundClearance: POSITIVE_NUMBER_RULE,
  characterMouseLookSensitivity: POSITIVE_NUMBER_RULE,
  characterTouchLookSensitivity: POSITIVE_NUMBER_RULE,
  characterZoomSensitivity: POSITIVE_NUMBER_RULE,
};
